import json, pathlib

def md(*l):
    return {"cell_type": "markdown", "metadata": {}, "source": [x + "\n" for x in l]}

def code(*l):
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": [x + "\n" for x in l]}

cells = [
md("# Domain-adapting MobileCLIP2-S2 on Pl@ntNet-300K",
   "",
   "**Runtime → Change runtime type → A100.**",
   "",
   "First run ~2.5–3.5 h (fetch 31.7 GB, resize, train). **Every run after that skips",
   "the download entirely** — the raw archive, a decode-fast copy of the dataset, and",
   "the training checkpoints all live on your Drive, so a disconnect costs minutes.",
   "",
   "## What this is testing",
   "",
   "The 17.9 MB encoder scores **0.6236** species top-1 on the 490-class catalogue;",
   "`plantclef24` at 43 MB scores **0.7671**. Three inference-side levers were measured",
   "and all three are null (`SMALL_FRONTIER_FINDINGS.md`), so that 14.4pp sits in the",
   "encoder's representation.",
   "",
   "What `plantclef24` *is*, is a DINOv2 ViT-B fine-tuned on 7,806 Pl@ntNet species —",
   "stock DINOv2 ViT-B is unremarkable here. **So the 43 MB advantage is domain",
   "adaptation, not size**, and nobody has done that to a 17.9 MB model. This runs the",
   "same recipe one encoder-scale down.",
   "",
   "Predictions are in `ADAPT_PREREG.md`, written before any run: **0.65–0.72** species",
   "against stock 0.6236, genus moving more than species, **0.74+ changes the size",
   "decision**.",
   "",
   "> **What it cannot show.** 530 of the 1,081 training species *are* the catalogue —",
   "> it was selected by image availability and absorbed 299,832 of the 306,146 images.",
   "> So the standard evaluation cannot tell *learned plants* from *learned this label",
   "> set*. Section 9 is the probe that can, and it is not optional."),

md("## 1. Environment and Drive",
   "",
   "Everything durable goes in one Drive folder: the compact dataset, the training",
   "checkpoints, and the final tower."),
code("!nvidia-smi --query-gpu=name,memory.total --format=csv,noheader",
     "!pip -q install open_clip_torch==2.32.0 pandas pyarrow"),
code("import os, json, time, tarfile, zipfile, pathlib, subprocess, shutil",
     "import numpy as np, pandas as pd, torch",
     "import torch.nn as nn, torch.nn.functional as F",
     "from torch.utils.data import Dataset, DataLoader",
     "from PIL import Image",
     "",
     "from google.colab import drive",
     "drive.mount('/content/drive')",
     "",
     "DRIVE = pathlib.Path('/content/drive/MyDrive/plantnet_adapt')",
     "DRIVE.mkdir(parents=True, exist_ok=True)",
     "DEV = 'cuda'",
     "torch.backends.cuda.matmul.allow_tf32 = True",
     "torch.backends.cudnn.allow_tf32 = True",
     "print(torch.__version__, torch.cuda.get_device_name(0))",
     "print('durable dir:', DRIVE)",
     "free = shutil.disk_usage('/content').free / 1e9",
     "print(f'local scratch free: {free:.0f} GB')"),

md("## 2. The research repo"),
code("REPO = pathlib.Path('narrowcast-plantid')",
     "if not REPO.exists():",
     "    subprocess.run(['git', 'clone', '-q',",
     "                    'https://github.com/semajyllek/narrowcast-plantid.git'], check=True)",
     "print(open(REPO / 'ADAPT_PREREG.md').read()[:900])"),

md("## 3. Dataset — two levels of Drive cache",
   "",
   "Both live on Drive, so **the Zenodo download happens exactly once, ever**:",
   "",
   "| on Drive | size | why |",
   "|---|---|---|",
   "| `plantnet_300K.zip` | 31.7 GB | the archive, so Zenodo is never hit twice |",
   "| `plantnet_288.tar` | ~10 GB | every image resized; what training actually reads |",
   "",
   "The resized copy is **not** a space compromise — it is a throughput one. A 17.9 MB",
   "model on an A100 is starved by JPEG decode long before it is starved by compute,",
   "and full-resolution Pl@ntNet images make the dataloader the bottleneck. 288 px on",
   "the short side against a 256 px training crop loses nothing the model can see, and",
   "roughly triples steps per second.",
   "",
   "A session restores from the tar in a few minutes. If the resize ever needs redoing,",
   "the raw zip is already local to Drive and Zenodo is not involved."),
code("RESIZE = 288",
     "RAW = DRIVE / 'plantnet_300K.zip'          # 31.7 GB, fetched once",
     "TAR = DRIVE / f'plantnet_{RESIZE}.tar'     # ~10 GB, what training reads",
     "SMALL = pathlib.Path('/content/plantnet_small')",
     "for f in (RAW, TAR):",
     "    print(f'{f.name:24s} {\"present\" if f.exists() else \"missing\"}')"),

code("def fetch_raw():",
     "    \"\"\"31.7 GB from Zenodo, straight onto Drive. Resumable, and runs once ever.\"\"\"",
     "    URL = 'https://zenodo.org/api/records/5645731/files/plantnet_300K.zip/content'",
     "    if RAW.exists() and RAW.stat().st_size > 31e9:",
     "        print(f'raw archive already on Drive ({RAW.stat().st_size/1e9:.1f} GB)')",
     "        return",
     "    print('downloading 31.7 GB to Drive (resumable -- just rerun if it drops)...')",
     "    subprocess.run(['curl', '-L', '-C', '-', '--retry', '5', '--retry-delay', '5',",
     "                    '-o', str(RAW), URL], check=True)",
     "    print(f'{RAW.stat().st_size/1e9:.1f} GB on Drive')",
     "",
     "",
     "def build_cache():",
     "    \"\"\"Extract the raw archive and write the resized tar to Drive. Runs once.\"\"\"",
     "    fetch_raw()",
     "    raw = pathlib.Path('/content/plantnet_raw')",
     "    if not raw.exists():",
     "        t0 = time.time()",
     "        with zipfile.ZipFile(RAW) as z:",
     "            z.extractall(raw)",
     "        print(f'extracted in {time.time()-t0:.0f}s')",
     "",
     "    images = next(p for p in raw.rglob('images') if p.is_dir())",
     "    files = sorted(images.rglob('*.jpg'))",
     "    # Everything is cached: the per-species cap is a training knob applied later,",
     "    # so it can be changed without rebuilding this.",
     "    print(f'{len(files):,} images to resize')",
     "",
     "    from multiprocessing import Pool",
     "    SMALL.mkdir(parents=True, exist_ok=True)",
     "    jobs = [(str(p), str(SMALL / p.parent.parent.name / p.parent.name / p.name))",
     "            for p in files]",
     "    for d in {pathlib.Path(j[1]).parent for j in jobs}:",
     "        d.mkdir(parents=True, exist_ok=True)",
     "    t0 = time.time()",
     "    with Pool(os.cpu_count()) as pool:",
     "        for i, _ in enumerate(pool.imap_unordered(_shrink, jobs, chunksize=256)):",
     "            if i % 25000 == 0:",
     "                print(f'  resized {i:,}/{len(jobs):,} ({time.time()-t0:.0f}s)', flush=True)",
     "    print(f'resized in {time.time()-t0:.0f}s')",
     "",
     "    t0 = time.time()",
     "    tmp = pathlib.Path('/content/cache.tar')",
     "    with tarfile.open(tmp, 'w') as t:",
     "        t.add(SMALL, arcname='.')",
     "    print(f'tar {tmp.stat().st_size/1e9:.1f} GB in {time.time()-t0:.0f}s; copying to Drive...')",
     "    shutil.copy(tmp, TAR)",
     "    print('cached at', TAR)"),

code("# module-level so multiprocessing can pickle it",
     "def _shrink(job):",
     "    src, dst = job",
     "    try:",
     "        im = Image.open(src).convert('RGB')",
     "        w, h = im.size",
     "        s = RESIZE / min(w, h)",
     "        if s < 1:",
     "            im = im.resize((round(w * s), round(h * s)), Image.BICUBIC)",
     "        im.save(dst, 'JPEG', quality=88)",
     "    except Exception:",
     "        pass"),

code("# TAR -> restore in minutes.  RAW on Drive -> resize only.  Neither -> fetch once.",
     "if TAR.exists():",
     "    if not SMALL.exists():",
     "        t0 = time.time()",
     "        SMALL.mkdir(parents=True, exist_ok=True)",
     "        with tarfile.open(TAR) as t:",
     "            t.extractall(SMALL)",
     "        print(f'restored from Drive in {time.time()-t0:.0f}s')",
     "    else:",
     "        print('already unpacked locally')",
     "else:",
     "    build_cache()",
     "",
     "n = sum(1 for _ in SMALL.rglob('*.jpg'))",
     "print(f'{n:,} images ready at {SMALL}')"),

md("## 4. The training set",
   "",
   "Labels come from the directory structure — `<split>/<species_id>/<id>.jpg` — rather",
   "than the metadata json, which the archive does not always carry. Pl@ntNet's own",
   "split is kept: `val` watches for overfitting and nothing is selected on `test`."),
code("MAX_PER_SPECIES = 200   # training-set balance knob; None uses every image",
     "",
     "rows = [(p.stem, p.parent.name, p.parent.parent.name, str(p))",
     "        for p in SMALL.rglob('*.jpg')]",
     "df = pd.DataFrame(rows, columns=['image_id', 'species_id', 'split', 'path'])",
     "assert set(df['split']) <= {'train', 'val', 'test'}, sorted(set(df['split']))[:6]",
     "",
     "classes = sorted(df['species_id'].unique())",
     "cls_idx = {c: i for i, c in enumerate(classes)}",
     "df['y'] = df['species_id'].map(cls_idx)",
     "",
     "# Applied to `train` only, and only here -- the cache holds everything, so this",
     "# can change without touching Drive. Pl@ntNet-300K is severely imbalanced and an",
     "# uncapped objective is dominated by a handful of species.",
     "if MAX_PER_SPECIES:",
     "    # shuffle-then-head rather than groupby.apply(sample): apply() consumes the",
     "    # key column in pandas 3 and this has to work on whatever Colab ships.",
     "    tr_rows = (df[df.split == 'train'].sample(frac=1, random_state=0)",
     "                 .groupby('species_id', sort=False).head(MAX_PER_SPECIES))",
     "    df = pd.concat([tr_rows, df[df.split != 'train']], ignore_index=True)",
     "",
     "print(f'{len(df):,} images, {len(classes)} species')",
     "print(df['split'].value_counts().to_dict())",
     "n_tr = df[df.split=='train'].groupby('species_id').size()",
     "print(f'train images/species: min {n_tr.min()} median {int(n_tr.median())} max {n_tr.max()}')"),

md("## 5. Model",
   "",
   "Only `.visual` is trained; a linear classifier is bolted on for the objective and",
   "discarded afterwards. The text tower is dropped — it never ships."),
code("import open_clip",
     "model, preprocess_train, preprocess_val = open_clip.create_model_and_transforms(",
     "    'hf-hub:timm/MobileCLIP2-S2-OpenCLIP')",
     "tower = model.visual.to(DEV)",
     "del model",
     "with torch.no_grad():",
     "    d = tower(torch.zeros(1, 3, 256, 256, device=DEV)).shape[-1]",
     "print('embedding dim', d,",
     "      f'| params {sum(p.numel() for p in tower.parameters())/1e6:.1f}M')",
     "head = nn.Linear(d, len(classes)).to(DEV)"),

md("## 6. Data pipeline"),
code("class PN(Dataset):",
     "    def __init__(self, frame, tf):",
     "        self.p = frame['path'].tolist(); self.y = frame['y'].tolist(); self.tf = tf",
     "    def __len__(self): return len(self.p)",
     "    def __getitem__(self, i):",
     "        try:",
     "            im = Image.open(self.p[i]).convert('RGB')",
     "        except Exception:",
     "            im = Image.new('RGB', (256, 256))",
     "        return self.tf(im), self.y[i]",
     "",
     "tr = DataLoader(PN(df[df.split=='train'], preprocess_train), batch_size=256,",
     "                shuffle=True, num_workers=8, pin_memory=True, drop_last=True,",
     "                persistent_workers=True)",
     "va = DataLoader(PN(df[df.split=='val'], preprocess_val), batch_size=512,",
     "                shuffle=False, num_workers=8, pin_memory=True)",
     "print(len(tr), 'train batches |', len(va), 'val batches')"),

md("## 7. Train, checkpointing to Drive every epoch",
   "",
   "Cross-entropy, AdamW, one-cycle, bf16. The tower gets a lower learning rate than",
   "the fresh head — a randomly initialised classifier would otherwise wreck the",
   "pretrained features in the first few hundred steps.",
   "",
   "**If the runtime dies, re-run this cell.** It reloads the last epoch from Drive and",
   "carries on."),
code("EPOCHS = 4",
     "CKPT = DRIVE / 'checkpoint.pt'",
     "",
     "opt = torch.optim.AdamW([{'params': tower.parameters(), 'lr': 1e-4},",
     "                         {'params': head.parameters(),  'lr': 1e-3}],",
     "                        weight_decay=0.05)",
     "sched = torch.optim.lr_scheduler.OneCycleLR(",
     "    opt, max_lr=[1e-4, 1e-3], total_steps=EPOCHS * len(tr), pct_start=0.1)",
     "",
     "start_ep = 0",
     "if CKPT.exists():",
     "    st = torch.load(CKPT, map_location=DEV)",
     "    tower.load_state_dict(st['tower']); head.load_state_dict(st['head'])",
     "    opt.load_state_dict(st['opt']); sched.load_state_dict(st['sched'])",
     "    start_ep = st['epoch'] + 1",
     "    print(f\"resumed from epoch {st['epoch']} (val {st['val']:.4f})\")",
     "",
     "def evaluate():",
     "    tower.eval(); head.eval(); ok = n = 0",
     "    with torch.no_grad(), torch.autocast('cuda', dtype=torch.bfloat16):",
     "        for x, y in va:",
     "            ok += (head(tower(x.to(DEV))).argmax(1).cpu() == y).sum().item(); n += len(y)",
     "    tower.train(); head.train()",
     "    return ok / max(n, 1)",
     "",
     "if start_ep == 0:",
     "    print(f'val top-1 before adaptation: {evaluate():.4f}')",
     "t0 = time.time()",
     "for ep in range(start_ep, EPOCHS):",
     "    tower.train(); head.train()",
     "    for i, (x, y) in enumerate(tr):",
     "        x, y = x.to(DEV, non_blocking=True), y.to(DEV, non_blocking=True)",
     "        with torch.autocast('cuda', dtype=torch.bfloat16):",
     "            loss = F.cross_entropy(head(tower(x)), y, label_smoothing=0.1)",
     "        opt.zero_grad(set_to_none=True); loss.backward(); opt.step(); sched.step()",
     "        if i % 100 == 0:",
     "            print(f'  ep{ep} {i}/{len(tr)} loss {loss.item():.3f} "
     "({time.time()-t0:.0f}s)', flush=True)",
     "    v = evaluate()",
     "    torch.save({'tower': tower.state_dict(), 'head': head.state_dict(),",
     "                'opt': opt.state_dict(), 'sched': sched.state_dict(),",
     "                'epoch': ep, 'val': v}, CKPT)",
     "    print(f'epoch {ep}: val top-1 {v:.4f} -- checkpointed to Drive', flush=True)"),

md("## 8. Save the tower",
   "",
   "The classifier is discarded: the product is a frozen feature extractor, and keeping",
   "a 1,081-way head would only invite someone to use it."),
code("OUT = DRIVE / 'mobileclip2_s2_plantnet.pt'",
     "torch.save({k: v.cpu() for k, v in tower.state_dict().items()}, OUT)",
     "print(f'{OUT} — {OUT.stat().st_size/1e6:.1f} MB (also on your Drive)')",
     "try:",
     "    from google.colab import files",
     "    files.download(str(OUT))",
     "except Exception as e:",
     "    print('download it from Drive instead:', e)"),

md("## 9. The transfer probe — not optional",
   "",
   "530 of the 1,081 training species **are** the catalogue, so a good headline score",
   "cannot distinguish *learned plants* from *learned this label set*. This probes the",
   "551 species the catalogue left behind: about nine images each, too thin to train",
   "on, enough to test on.",
   "",
   "**If adapted does not beat stock here, it learned the catalogue rather than plants**,",
   "and no general small-plant-encoder claim is supported."),
code("cat_ids = set(json.load(open(REPO / 'catalogue_species.json'))['species'])",
     "heldout = df[~df.species_id.isin(cat_ids)]",
     "print(f'catalogue {len(cat_ids)} species | held out "
     "{heldout.species_id.nunique()} species, {len(heldout):,} images')"),
code("def embed_all(tw, frame):",
     "    dl = DataLoader(PN(frame, preprocess_val), batch_size=512, num_workers=8)",
     "    tw.eval(); out = []",
     "    with torch.no_grad(), torch.autocast('cuda', dtype=torch.bfloat16):",
     "        for x, _ in dl:",
     "            out.append(F.normalize(tw(x.to(DEV)).float(), dim=-1).cpu().numpy())",
     "    return np.vstack(out)",
     "",
     "def probe(X, y, seed=0):",
     "    from sklearn.linear_model import LogisticRegression",
     "    rng = np.random.default_rng(seed); idx = rng.permutation(len(X))",
     "    cut = int(0.6 * len(X)); a, b = idx[:cut], idx[cut:]",
     "    clf = LogisticRegression(max_iter=2000, C=10.0).fit(X[a], y[a])",
     "    return float((clf.predict(X[b]) == y[b]).mean())",
     "",
     "sub = heldout.groupby('species_id').filter(lambda g: len(g) >= 6)",
     "y = sub['species_id'].astype('category').cat.codes.to_numpy()",
     "print(f'probing {len(sub):,} images over {sub.species_id.nunique()} species')",
     "",
     "stock, _, _ = open_clip.create_model_and_transforms('hf-hub:timm/MobileCLIP2-S2-OpenCLIP')",
     "a = probe(embed_all(stock.visual.to(DEV), sub), y)",
     "b = probe(embed_all(tower, sub), y)",
     "print(f'held-out species linear probe — stock {a:.4f} | adapted {b:.4f} | {b-a:+.4f}')",
     "print('Adapted must beat stock here, or it learned the catalogue rather than plants.')"),

md("## 10. Back on your machine",
   "",
   "```bash",
   "mkdir -p data/processed/adapted",
   "cp ~/Downloads/mobileclip2_s2_plantnet.pt data/processed/adapted/",
   "",
   "PYTHONPATH=. .venv-mps/bin/python -c \"",
   "from plantid.features import embed_catalog, embed_inat, embed_background",
   "for f in (embed_catalog.main, embed_inat.main, embed_background.main):",
   "    f('mobileclip2_s2_ft')\"",
   "",
   "PYTHONPATH=. .venv/bin/python -m plantid.eval.rejection --variant mobileclip2_s2_ft",
   "```",
   "",
   "Compare against `mobileclip2_s2` 0.6236 / 0.8122, `plantclef24` 0.7671 / 0.9258,",
   "`bioclip2_cml4` 0.8370 / 0.9735 — and against the predictions in `ADAPT_PREREG.md`."),
]

nb = {"cells": cells,
      "metadata": {"accelerator": "GPU",
                   "colab": {"provenance": [], "gpuType": "A100"},
                   "kernelspec": {"display_name": "Python 3", "name": "python3"},
                   "language_info": {"name": "python"}},
      "nbformat": 4, "nbformat_minor": 0}

out = pathlib.Path('/Users/jameskelly/Documents/narrowcast-plantid/notebooks/adapt_s2_colab.ipynb')
out.write_text(json.dumps(nb, indent=1))
print("wrote", out, len(cells), "cells")
